version: '3.7'
services:

  db:
    image:  postgres:13
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

    restart: always


  app:
    build: ./project
    container_name: app
    depends_on:
      - db
    volumes:
    - type: bind
      source: ./project/migrations/versions
      target: /code/project/migrations/versions
      volume:
        nocopy: true

    env_file:
      - .env
    ports: 
      - "8008:8000"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./pgadmin:/var/lib/pgadmin

volumes:
  data: