"""Add 2 column cpc and cpm

Revision ID: a63aeb1f02b1
Revises: ad5de38ea563
Create Date: 2022-05-15 17:14:49.409991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63aeb1f02b1'
down_revision = 'ad5de38ea563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statics', sa.Column('cpc', sa.Numeric(), nullable=True))
    op.add_column('statics', sa.Column('cpm', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statics', 'cpm')
    op.drop_column('statics', 'cpc')
    # ### end Alembic commands ###
